name: i18n

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lokalise-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: brew tap lokalise/cli-2

      - run: brew install lokalise2

      - name: upload app/locales/en.json
        run: lokalise2 file upload --file app/locales/en.json --lang-iso=en --project-id=${{ secrets.LOKALISE_PROJECT_ID }} --token=${{ secrets.LOKALISE_TOKEN }}

      - name: upload ios/en.lproj/InfoPlist.strings
        run: lokalise2 file upload --file ios/en.lproj/InfoPlist.strings --lang-iso=en --project-id=${{ secrets.LOKALISE_PROJECT_ID }} --token=${{ secrets.LOKALISE_TOKEN }}

      - name: upload ios/en.lproj/Localizable.strings
        run: lokalise2 file upload --file ios/en.lproj/Localizable.strings --lang-iso=en --project-id=${{ secrets.LOKALISE_PROJECT_ID }} --token=${{ secrets.LOKALISE_TOKEN }}

      - name: upload android/app/src/main/res/values/strings.xml
        run: lokalise2 file upload --file android/app/src/main/res/values/strings.xml --lang-iso=en --project-id=${{ secrets.LOKALISE_PROJECT_ID }} --token=${{ secrets.LOKALISE_TOKEN }}

